import numpy as np
import matplotlib.pyplot as plt
from qiskit_ibm_runtime import QiskitRuntimeService, EstimatorV2 as Estimator
from qiskit.circuit.library import efficient_su2
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from qiskit_algorithms import VarQITE, TimeEvolutionProblem
from qiskit_algorithms.time_evolvers.variational import ImaginaryMcLachlanPrinciple

# Chemistry Imports
from qiskit_nature.second_q.drivers import PySCFDriver
from qiskit_nature.second_q.mappers import ParityMapper

# IBM auth and backend setup
service = QiskitRuntimeService(channel="ibm_quantum_platform")
backend = service.least_busy(operational=True, simulator=False)
print(f"Targeting Backend: {backend.name} ({backend.num_qubits} qubits)")

# molecule definition (logical 2-qubit space)
driver = PySCFDriver(atom="H 0 0 0; H 0 0 0.735", basis="sto3g")
problem = driver.run()
mapper = ParityMapper(num_particles=problem.num_particles)
h2_hamiltonian = mapper.map(problem.hamiltonian.second_q_op())

# ansatz (logical 2-qubit space)
ansatz = efficient_su2(num_qubits=h2_hamiltonian.num_qubits, reps=1) # for increased accuracy (but more noise) change reps to 2 or 3
init_params = np.full(ansatz.num_parameters, 0.01) 

# runtime setup
estimator = Estimator(mode=backend)
estimator.options.resilience_level = 1 # for increased accuracy adjust to 2 for zero noise extrapolation
estimator.options.default_shots = 1024 # for increased accuracy adjust higher to 4096 or 10000


# VarQITE needs logical circuits for calculus. IBM needs physical circuits. This intercepts jobs leaving VarQITE and translates them on the fly.
pm = generate_preset_pass_manager(optimization_level=1, backend=backend) # for increased accuracy change optimization_levle to 3
original_run = estimator.run

def transpiled_run(pubs, **kwargs):
    t_pubs = []
    for pub in pubs:
        # Extract the logical components generated by VarQITE
        circuit, obs = pub[0], pub[1]
        params = pub[2] if len(pub) > 2 else None

        # 1. Transpile the circuit to 156 qubits
        t_qc = pm.run(circuit)

        # 2. Pad the observable(s) to 156 qubits
        if isinstance(obs, list):
            t_obs = [o.apply_layout(t_qc.layout, num_qubits=backend.num_qubits) for o in obs]
        else:
            t_obs = obs.apply_layout(t_qc.layout, num_qubits=backend.num_qubits)

        # 3. Re-package the hardware-ready pub
        if params is not None:
            t_pubs.append((t_qc, t_obs, params))
        else:
            t_pubs.append((t_qc, t_obs))
            
    return original_run(t_pubs, **kwargs)

# Patch the estimator to use above interceptor
estimator.run = transpiled_run


var_principle = ImaginaryMcLachlanPrinciple()

# 5. define evolution problem (using logical operators)
total_imaginary_time = 2.0 # for increased accuracy (and time and noise) increase to 5 or 10
num_steps = 5 # for increased accuracy (and time and noise) increase to 10 or 20

evolution_problem = TimeEvolutionProblem(
    h2_hamiltonian, 
    time=total_imaginary_time, 
    aux_operators=[h2_hamiltonian]
)

# 6. execute QITE
print(f"Starting QITE on {backend.name}. Passing logical math to the algorithm...")
var_qite = VarQITE(
    ansatz=ansatz, # <--- We pass the pure 2-qubit logical ansatz here
    initial_parameters=init_params, 
    variational_principle=var_principle, 
    estimator=estimator, 
    num_timesteps=num_steps
)

evolution_result = var_qite.evolve(evolution_problem)
print("Evolution complete.")

# 7. results and plotting
energies = [obs[0][0] + problem.nuclear_repulsion_energy for obs in evolution_result.observables]
times = np.linspace(0, total_imaginary_time, len(energies))

print(f"\nFinal Ground State Energy: {energies[-1]:.6f} Hartree")
print(f"Theoretical Target: -1.137 Hartree")

plt.figure(figsize=(8, 5))
plt.plot(times, energies, 'o-', label='QITE (Real Hardware)')
plt.axhline(y=-1.137, color='r', linestyle='--', label='Target')
plt.xlabel('Imaginary Time (tau)')
plt.ylabel('Total Energy (Hartree)')
plt.title(f'H2 Cooling on {backend.name}')
plt.legend()
plt.grid(True)
plt.show()
